### ISSUE TITLE
vdaf: Consider removing `PrepareTransition::Fail` variant

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#221]
I've found using this a bit awkward. I think it would be cleaner to have a `prep_next()` return a `Result<PrepareTransition, VdafError>`, as this allows us to handle failures the same way we do at every other point in the processing chain.

**Comment by tgeoghegan** [comment]
I like the idea of handling errors as errors, and also approve if this change would make your life easier. I'm not sure it would have a huge impact on how Janus uses this. Right now, we have a match statement like:

```
match foo.prepare_step(...) {
    PrepareTransition::Continue(...) => { ... }
    PrepareTransition::Finished => { ... }
    PrepareTransition::Failed(err) => { ... }
}
```
[example](https://github.com/divviup/janus/blob/54ba8e759e35996a6ea8773aa5f72973d19d4712/janus_server/src/aggregator.rs#L1022)

If we did as proposed (`fn prepare_step(...) -> Result<PrepareTransition, Error>`, then I think we instead would do:

```
match foo.prepare_step(...) {
    Ok(PrepareTransition::Continue(...)) => { ... }
    Ok(PrepareTransition::Finished) => { ... }
    Err(err) => { ... }
}
```

Which, to me, is just about the same thing. We can't just do `foo.prepare_step(...)?` and propagate the error up because we're always in a loop handling a list of prepare transitions, and any one of them failing shouldn't cause us to give up on the rest.
