### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#237]
While cleaning up the documentation for Prio3, I noticed each Prio3 instance uses `new()` as its constructor. The documentation renders an ugly list of these methods as acting on `Prio3`, rather than the type alias for each instance:
![image](https://user-images.githubusercontent.com/3453007/170585567-636dbdaf-2c1f-4d00-8187-ef477e1f543d.png)

Any way to clean this up?

**Comment by BranLwyd** [comment]
A couple of suggestions for consideration, I've attempted to highlight the tradeoffs in each one -- none of these are really great:

1. Make these free functions (e.g. `vdaf::new_prio3_aes128_count(...)`). This would resolve the issue in a straightforward way but would also make these functions less discoverable to folks looking at the `Prio3` type. (I suppose the `Prio3` documentation could reference these functions.)

[I wanted to make a similar suggestion to rename these functions and place them on `Prio3` directly so that we could type e.g. `Prio3::new_aes128_count(...)`, but I couldn't figure out how to make Rust not require the type annotations even though they logically aren't needed by the constructor method.]

2. Switch from using type aliases to newtypes. This would resolve the issue but would probably require an infeasible amount of re-exporting of functions & types, unless you wrote a macro to produce the desired specializations (which itself may be too much effort).

**Comment by cjpatton** [comment]
I think I would prefer (1.)
