### ISSUE TITLE
Clarify expectations for decoding Prepare{Share,Message}.

### ISSUE THREAD

**Issue by BranLwyd** [divviup/libprio-rs#245]
Currently, decoding `PrepareShare` & `PrepareMessage` require a `PrepareState` parameter: https://github.com/divviup/libprio-rs/blob/8f1da11b3bd8ecc462594a80302bea76ffc9300a/src/vdaf.rs#L152-L156

It would be helpful to clarify the expectations on how this `PrepareState` parameter relates to the `Prepare{Share,Message}` being decoded. For example, is it acceptable to decode one aggregator's prepare share with a parameter that is a different aggregator's prepare state? (Janus currently does this: https://github.com/divviup/janus/blob/bb9d2bba33fcd122dc0d4b02bb33df19f5a9f9bf/janus_server/src/bin/aggregation_job_driver.rs#L629-L631.)

**Comment by cjpatton** [comment]
I'm a bit confused about what's going in the cited code. It looks like the leader is processing an AggregateResp the helper, however you appear to be iterating over the sequence of "helper steps". Moreover, shouldn't this be an PrepareShare, not a PrepareMessage? (See https://github.com/divviup/libprio-rs/pull/242.)

That said, in order to decode a prep share from its peer, the aggregator will need to know what state it is is in.

**Comment by divergentdave** [comment]
The loop is iterating over both leader transitions and helper transitions, zipped together (with some additional context).

Janus is still on prio 0.7.1, so we haven't picked up `PrepareShare` yet.

I think `PrepareState` as a decoding parameter makes sense here. Each aggregator's prepare state must be kept secret, so necessarily each aggregator will use its own state as the context to encode and decode all prepare shares.

One caveat as a consequence of this: if any VDAF ever wanted to use different encodings (i.e. compressed versus not) of prepare shares for different aggregators, that would require adding the aggregator ID to the decoding parameter somehow, or explicitly encoding that distinction between types as part of the wire format. For now, such a VDAF seems unlikely to me.
