### ISSUE TITLE
Subdivide library

### ISSUE THREAD

**Issue by simon-friedberger** [divviup/libprio-rs#252]
Related to #241 I would like to propose that we split up the library somewhat.

It would be useful to have the VDAF part and possibly the TLS encoding part in many implementations but presumably a lot of people won't need the Prio2 part anymore which seems to be what needs ring, aes-gcm.

**Comment by BranLwyd** [comment]
👍🏻 I'd support splitting out different parts of the library. This sounds like a use case for Rust crate features, which would allow consumers of the library to enable/disable the portions of the library that they need.

This is (obviously) a breaking change. We are still at `<1.0.0`, I think it would still be helpful to do this in a patch rather than minor release (though there is nothing in semver forcing any `<1.0.0` change from being breaking), and call it out clearly in release notes.

**Comment by cjpatton** [comment]
This might be partially solved by https://github.com/divviup/libprio-rs/pull/240. @tgeoghegan pointed out that prio_server might be able to be refactored to use the `Prio2` VDAF directly, hence allowing us to remove at least some of the v2 server code from this repository.

This would entail deployment changes that I assume would be needed to be validated in production. I guess the sequence of events might be:
1. Release prio 0.8.x with #240
2. Upgrade prio_server to 0.8.x
3. Deploy upgraded prio_server to some canary thing, make sure there's no regression
4. Release prio 0.8.(x+1) with v2 server bits removed

**Comment by tgeoghegan** [comment]
IIUC, after #240, the only parts of ENPA/Priov2 that aren't handled by the `Prio2` VDAF is ECIES encryption and providing the ingestion server's query randomness. The question is: do we move those bits into `prio-server`, or produce a further crate that depends on `prio` and uses the `Prio2` VDAF to implement ENPA, exposing the same interface `prio-server` currently uses. I lean towards the former, because I'm not aware of anything besides `prio-server` that would use this new crate, and so I'd rather avoid the overhead of maintaining an extra project, but I'm floating the notion so that any potential users of this hypothetical new ENPA/Prio2 crate can sound off here.

**Comment by divergentdave** [comment]
We eliminated the ring and aes-gcm dependencies in #660 by dropping the ENPA interfaces entirely.
