### ISSUE TITLE
How to integrate our custom type into prio

### ISSUE THREAD

**Issue by MxmUrw** [divviup/libprio-rs#257]
We were told that we could integrate our custom type for fixed-point vectors with bounded norm directly into the libprio-rs repository. See [this readme](https://github.com/dpsa-project/libprio-rs) for some details about our type. It is pretty specific to our concrete use-case, so it might be worth discussing whether it really makes sense to integrate it - or at least in what form.

Nevertheless, our prototype is working, and we are only waiting for a small issue (#256) to be resolved. So, let's assume that we want to get our type into prio. Here are the questions that we currently face:
 1. Where in the code base should it reside? I think it makes sense to have our own module, where should that be?
 2. We use the [fixed crate](https://docs.rs/fixed/latest/fixed/). Is it ok to add it as dependency?
 3. Should we think about more generic use-cases? We are working with fixed point numbers after all, something which should be useful much more broadly. But it seems difficult to write code generically:
    - Signed vs unsigned fixed numbers would use different encodings.
    - Different use-cases might require different fixed-point type implementations / libraries.
    - Even restricting to the `fixed` crate, our use-case dictates us a specific fixed-point format (1 bit encodes value before the point, rest of the bits encode fractional value). Other applications would probably need other formats.
 4. We might include some (less restrictive) variants of our prio type, for example fixed-point vectors without a bounded-norm-check. But it seems that this would require some amount of code duplication. As such, I would say that this wouldn't really be useful?
 5. Are there plans to make prio types more composable?

**EDIT**: Our next steps involve adding differential privacy. I am sure there must have been thoughts regarding this topic, so it might be relevant to this discussion.

**Comment by tgeoghegan** [comment]
I agree with @cjpatton, with just two things to add. First, you could hide your new bits behind a [cargo feature](https://doc.rust-lang.org/cargo/reference/features.html) so that not every dependent of `prio` has to take on the `fixed` dependency or the new code you're adding.

Second, with regards to DP: I agree again with Chris in that VDAF is unlikely to say anything about applying DP before a measurement is sharded or compensating for it after aggregate shares are merged, so I wouldn't expect anything to do with DP to appear on trait `prio::vdaf::Vdaf` (or the `Client, Aggregator, Collector` traits). However, it might make sense for the concrete type you define for your new VDAF's `Vdaf::Measurement` associated type to expose support for DP.

I also think that maybe we should "wait and see" what VDAF ends up specifying about applying DP to aggregate shares. When libprio implements that, we might end up doing 90% of the work needed to add DP noise to measurements.

**Comment by cjpatton** [comment]
Closed by #283!
