### ISSUE TITLE
Consider removing dependency on `fixed`

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#369]
The FLP circuit `FixedPointBoundedL2VecSum` currently takes in a vector of generic fixed point numbers, implementing `fixed::Fixed`. This has been a barrier for library consumers that audit transitive dependencies, as the `fixed` crate has a substantial amount of logic we don't use.

We should consider changing the input type to, say, `Vec<i64>`, with the additional semantics that fixed point inputs should be converted/premultiplied before being passed in as integers. We could then replace the fixed-point math in the sharding and unsharding routines with appropriate integer shifts. This would allow us to drop the dependency.

As an alternative solution, we could place both the `fixed` dependency and the related Prio instantiation behind a Cargo feature.

cc @ooovi @MxmUrw

**Comment by MxmUrw** [comment]
Yes, either solution would be fine with us. In particular, we don't use any fixed-point math from the `fixed` crate - internally our number representation is slightly different anyways. The only reason that we chose to use the types from that crate is because they provide an interface where the semantic of the values is well-documented. From this perspective the second solution would be preferable.

A previous mention of this issue was [here](https://github.com/divviup/libprio-rs/pull/283#issuecomment-1242288749), with our reply [here](https://github.com/divviup/libprio-rs/pull/283#issuecomment-1243900148).

Maybe @tgeoghegan or @cjpatton have an opinion?
