### ISSUE TITLE
Provide `cargo vet` audit.

### ISSUE THREAD

**Issue by branlwyd** [divviup/libprio-rs#396]
`cargo vet` is an auditing tool for Rust crates: https://mozilla.github.io/cargo-vet

Mozilla has requested that a "safe to run" and "safe to deploy" audits for `libprio-rs`. "Safe to run" implies freedom from intentionally-malicious code (e.g. memory snoopers, exploits, bitcoin miners, ...). "Safe to deploy" implies safety even in the presence of untrusted inputs.

Mozilla is not currently requesting a "semantic correctness" audit. We might still do this, perhaps once `libprio-rs` is more mature.

**Comment by divergentdave** [comment]
Here are some notes on the subject from a read-through of the manual and some brief experimentation:

Because we support multiple release branches simultaneously, we'll need to re-import our own audits. We could have all branches re-import audits from main, or we could bounce it through a `cargo vet aggregate` workflow.

I tried out importing Firefox and Zcash audit repositories, and I found that the overlap only covered ~10% of the audit backlog, by lines.

We should add a configuration stanza to set `policy.prio-binaries.criteria = "safe-to-run"`, since this provides development-only tools. (Then, I think we need to set `policy.prio.criteria = "safe-to-deploy"` to keep auditing its dependencies to that standard. This could possibly be a bug, or I may just not understand how default criteria work.)

I'd like to run `cargo vet` with the option `--no-all-features`, because Firefox uses this configuration, and auditing `ring` up front is a daunting proposition. However, this has no effect, presumably because `prio-binaries` enables features on `prio`, and they get unified with those that `cargo vet` sets on `prio` directly. We may have to remove `prio-binaries` from the workspace to get this to work as intended, since there's no `--package` option.

By default, `cargo vet init` sets `policy.prio.audit-as-crates-io = false, meaning that it won't expect audits on `prio` itself, since it's first party code. While we could override this, and record audits after every `prio` release, I'm not sure whether we'd want to. There's more on the rationale around reviewing first party code [here](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html#self-certification) and [here](https://mozilla.github.io/cargo-vet/first-party-code.html).

**Comment by bholley** [comment]
> Here are some notes on the subject from a read-through of the manual and some brief experimentation:

Thanks for working on this.

> Because we support multiple release branches simultaneously, we'll need to re-import our own audits. We could have all branches re-import audits from main, or we could bounce it through a `cargo vet aggregate` workflow.

One thing that might be helpful for managing audits of your own crates is the upcoming [wildcard audit](https://github.com/mozilla/cargo-vet/issues/353) feature, which should be released sometime in January.

> I tried out importing Firefox and Zcash audit repositories, and I found that the overlap only covered ~10% of the audit backlog, by lines.

Two other major users are the Byetecode Alliance and Embark Studios (both of which we're importing in Firefox). I just opened a [PR](https://github.com/mozilla/cargo-vet/issues/353) to add them to the registry, but worth seeing if they improve your coverage.

> We should add a configuration stanza to set `policy.prio-binaries.criteria = "safe-to-run"`, since this provides development-only tools. (Then, I think we need to set `policy.prio.criteria = "safe-to-deploy"` to keep auditing its dependencies to that standard. This could possibly be a bug, or I may just not understand how default criteria work.)

By default, all the workspace roots should require safe-to-deploy so you shouldn't need to manually specify it. If that's not happening please file an issue.

> I'd like to run `cargo vet` with the option `--no-all-features`, because Firefox uses this configuration, and auditing `ring` up front is a daunting proposition.

You can also just leave ring in your exemptions list. Cargo-vet is intended to be easy to set up by moving all existing dependencies to the exemptions list, and then letting you deal with them over time.

> However, this has no effect, presumably because `prio-binaries` enables features on `prio`, and they get unified with those that `cargo vet` sets on `prio` directly. We may have to remove `prio-binaries` from the workspace to get this to work as intended, since there's no `--package` option.
> 
> By default, `cargo vet init` sets `policy.prio.audit-as-crates-io = false, meaning that it won't expect audits on `prio`itself, since it's first party code. While we could override this, and record audits after every`prio` release, I'm not sure whether we'd want to. There's more on the rationale around reviewing first party code [here](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html#self-certification) and [here](https://mozilla.github.io/cargo-vet/first-party-code.html).

Yeah, we have this same papercut with the various first-party crates we publish out of mozilla-central. For now we've just been marking them as `audit-as-crates-io=true` and then recording an audit whenever we release, but the wildcard audit mechanism described above should eliminate the busywork.

**Comment by divergentdave** [comment]
Nice, importing those two additional sources knocks another 10% off of the backlog, the system works! (`ring` and its transitive dependencies seem to make up the bulk of our backlog) I'll look into the policy issue some more and file an issue.

**Comment by divergentdave** [comment]
`cargo-vet` 0.5.1 is now available, we could upgrade and then write a wildcard audit for prio. (I had missed this until now because I'm just watching GitHub releases from the repository, and versions since 0.3 only have git tags and crates.io crate versions)

**Comment by bholley** [comment]
That would be awesome, thank you!
