### ISSUE TITLE
Timeline for removal of PrgAes128

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#474]
Following up on a [comment on #471](https://github.com/divviup/libprio-rs/pull/471#pullrequestreview-1316626093): after all our VDAF-04 changes are done, the main internal user of `PrgAes128` (more specifically, `SeedStreamAes128`) will be the ENPA API. Should we keep this PRG around for now for these purposes, or remove both in the next release? cc @tgeoghegan

I'm inclined to leave the PRG for now, and drop it with the ENPA APIs at a later date, in the same release where we rearrange modules and introduce the new crate name.

**Comment by cjpatton** [comment]
I would appreciate continuing support for `Prio2` post-ENPA. This requires `SeedStreamAes128`.

**Comment by tgeoghegan** [comment]
OK, so I guess the idea is that if someone were to write a draft specifying the `Prio2` VDAF, they'd also have to specify `PrgAes128`?

In any case, I don't see a reason to break `Prio2`, since it is going to be run in production. I think we should hang on to `PrgAes128`, even if it's not formally specified anywhere.

**Comment by cjpatton** [comment]
`PrgAes128` is not used by `Prio2` directly: We could get away just the seed stream bits. I think it's worth cutting it, or at the very least marking it as deprecated in the next release.

**Comment by cjpatton** [comment]
Closed by https://github.com/divviup/libprio-rs/pull/721.
