### ISSUE TITLE
Comparisons between field elements

### ISSUE THREAD

**Issue by jimouris** [divviup/libprio-rs#810]
Hello,

I'm using `Field64` and I'm trying to do a simple comparison between two field elements since it seems that it is supported in the [documentation](https://docs.rs/prio/0.15.3/prio/field/struct.Field64.html#method.cmp). However, the code below outputs `false`:

```rust
use prio::field::Field64;

fn main() {
    let val_1 = Field64::from(10u64);
    let val_2 = Field64::from(2u64);
    let res = val_1 >= val_2;
    println!("{} >= {}? {}", val_1, val_2, res);
}
```

Now, if we replace the comparison with `let res = u64::from(val_1) >= u64::from(val_2);`, it works as expected.

cc: @cjpatton

**Comment by cjpatton** [comment]
This is due to an incorrect implementation of `PartialOrd` (or `Ord`?): https://github.com/divviup/libprio-rs/blob/main/src/field.rs#L385

The derived implementation here operates on the internal representation of field elements, which is not comparable the way the integer representation is. The correct implementation would first convert to `Field::Integer` then do the comparison.

However, we should consider not implementing `PartialOrd` for `Field`. The reason is that conversion to `Field::Integer` is expensive for the current implementation. If the user needs this, we should force them to convert first.
